### PR TITLE
Implementing Localise By topic and No go nodes exceptions

### PR DESCRIPTION
**Pull request by Jailander**

### CODE REVIEW

**Comment by hawesie** [comment]
How can we stress test this?

**Comment by Jailander** [comment]
you have to add a JSON string like this {'topic':'/name_of_the_topic', 'field':'field on the msg', 'val':value for that field} on the localise by topic on node you want to localise, e.g. ChargingPoint where the string would look like {'topic':'/battery_state', 'field':'charging', 'val':true} 

Note: I am writing this on my phone from the top of my head, I will send an example and maybe an script to set this value tomorrow when I go to the lab.

**Comment by Jailander** [comment]
yes that was for the localise by topic thing, the no go nodes is not fully implemented as I mentioned in #210 but you can test them adding unconnected nodes and the no_go tag to these nodes (using add tag service) topological localisation should never consider these nodes as closest nodes unless the robot is inside the influence zone of the nodes

**Comment by Jailander** [comment]
about the stress test I left my sim running constantly with this, the best test is checking that topological loc works as usual, then for the charging you should see that the /closest_node and /current_node topics only say ChargingStaion when /battery_state is chraging

**Comment by bfalacerda** [comment]
This doesn't seem to be working. The top window is `/current_node` and the middle window is `/closest_node`. 

screenshot from 2015-04-06 15 05 17

**Comment by bfalacerda** [comment]
Also, the robot eventually starts charging, and the `/battery_state/charging` becomes `true` (which should be a success), but the action doesnt succeed and he tries the "Do move_base to ChargingPoint" thing:

```
 INFO] [1428329510.690733615]: Charging service is measuring robot position
[ INFO] [1428329515.135734835]: Charging service is attempting to dock
[INFO] [WallTime: 1428329518.020692] new node reached ChargingPoint
[INFO] [WallTime: 1428329518.057321] new node reached ChargingPoint
[ INFO] [1428329519.770340652]: Charging service is waiting for charger signal
[ INFO] [1428329524.359577206]: Position of the robot relative to the charging station is 0.006 -0.001 -0.004, i.e. 6 mm from the desired position->
[ INFO] [1428329524.391998500]: Charging service is feeding
[INFO] [WallTime: 1428329524.551722] State machine terminating 'NAVIGATION':'succeeded':'succeeded'
[INFO] [WallTime: 1428329524.552262] Concurrent state 'NAV_SM' returned outcome 'succeeded' on termination.
[INFO] [WallTime: 1428329524.557250] Concurrent state 'stuck_on_carpet' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1428329524.564370] Concurrent state 'service_pause_nav' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1428329524.568597] Concurrent state 'pad_pause_nav' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1428329524.574021] Concurrent state 'bumper' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1428329524.574432] Concurrent state 'magnetic_strip' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1428329524.576787] Concurrent Outcomes: {'stuck_on_carpet': 'preempted', 'magnetic_strip': 'preempted', 'service_pause_nav': 'preemp$
ed', 'bumper': 'preempted', 'pad_pause_nav': 'preempted', 'NAV_SM': 'succeeded'}
[INFO] [WallTime: 1428329524.577150] State machine terminating 'MONITORED_NAV':'succeeded':'succeeded'
[INFO] [WallTime: 1428329524.577540] SUCCEEDED
[INFO] [WallTime: 1428329524.721177] Waiting for services...
[INFO] [WallTime: 1428329524.731419] Done
Do move_base to ChargingPoint
[INFO] [WallTime: 1428329525.079725] State machine starting in initial state 'MONITORED_NAV' with userdata: 
        ['goal', 'result']
[INFO] [WallTime: 1428329525.080248] Concurrence starting with userdata: 
        ['goal']
[INFO] [WallTime: 1428329525.083940] State machine starting in initial state 'NAVIGATION' with userdata: 
        ['goal', 'n_fails']
[ WARN] [1428329530.211722012]: Clearing costmap to unstuck robot (2.000000m).
[ WARN] [1428329530.497998002]: Map update loop missed its desired rate of 5.0000Hz... the loop actually took 0.2107 seconds
[ WARN] [1428329530.612110771]: Clearing costmap to unstuck robot (0.000000m).
[ERROR] [1428329530.911878742]: Aborting because a valid plan could not be found. Even after executing all recovery behaviors
```

**Comment by Jailander** [comment]
hmmm ok, I only tested on simulation, yes it may happen that if the battery is full it is not  charging anymore and will tell you that is not at the ChargingStation, I'll try to find a fix if this is the behaviour you are experiencing, but I'm not sure if that is it just to be sure the robot should only say that ChargingPoint is /current_node when the topic value coincides with the value you set, also it should also consider it /closest_node when is at the node.

I just found a reason for the move base thing is in this line https://github.com/strands-project/strands_navigation/blob/indigo-devel/topological_navigation/scripts/execute_policy_server.py#L323 I'll fix tomorrow by adding the condition of only doing so when there is a move_base action in one edge

**Comment by bfalacerda** [comment]
what is happening here is the other way around: he tells me he is in ChargingStation, but he is not charging yet

**Comment by Jailander** [comment]
Did you put the localise by topic string?

**Comment by bfalacerda** [comment]
sorry, completely forgot... You add that json string to the node entry in mongo? Is the script to add it that you mentioned available somewhere?

**Comment by Jailander** [comment]
No sorry I didn't manage to find any free tine to work will do it tomorrow morning still on the phone

**Comment by bfalacerda** [comment]
i'm not being able to add the string. I added  `"localise_by_topic" : "{ 'topic':'/battery_state', 'field':'charging', 'val':true }"` but i get 

```
[INFO] [WallTime: 1428405650.876425] Waiting for Topological map ...
[ERROR] [WallTime: 1428405650.926127] bad callback: <bound method TopologicalNavLoc.MapCallback of <__main__.TopologicalNavLoc object at 0x7f02f2b65a1$
>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 702, in _invoke_callback
    cb(msg)
  File "/home/strands/1f_ws/src/strands_navigation/topological_navigation/scripts/localisation.py", line 138, in MapCallback
    a= json.loads(i.localise_by_topic)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 1 column 3 (char 2)
```

Looking [here](https://github.com/strands-project/strands_navigation/pull/216/files#diff-e0577a4bc920b8757a69c63123bc47d0R141) , I tried to replace the 'topic' key with 'name', but I get the same error anyway.

@Jailander what am I doing wrong? Is the script available?

**Comment by Jailander** [comment]
wait commiting it now

**Comment by Jailander** [comment]
as usual `rosrun topological_utils migrate.py` should do it to all your maps

**Comment by Jailander** [comment]
the string looks like this 

``` JSON
{"topic":"/battery_state","field":"charging", "val": true}
```

you have to add back slash in robomongo like this
`{\"topic\":\"/battery_state\",\"field\":\"charging\", \"val\": true}`
it should work I've tested extensively

migrate script less tested but tested

**Comment by Jailander** [comment]
the field name is topic as you can see [here](https://github.com/strands-project/strands_navigation/pull/216/files#diff-e0577a4bc920b8757a69c63123bc47d0R50)

**Comment by Jailander** [comment]
last commit fixes #208

**Comment by marc-hanheide** [comment]
I'll leave it to @bfalacerda to test on Bob and report if this works before merging.

**Comment by bfalacerda** [comment]
works nicely :)

**Comment by Jailander** [comment]
:+1:

**Pull request merged**
