### PR TITLE
sending the robot to waypoint when in the influence area of the target n...

### PR DESCRIPTION
**Pull request by Jailander**
...ode

### CODE REVIEW

**Comment by marc-hanheide** [comment]
shall this still be merged, as it will effect #193? You guys really make me struggle here ;-)

**Comment by Jailander** [comment]
Hmmm, not sure, I don't see this on @bfalacerda PR, but it should be merged on his fork as he tested part of this :/ I'm not sure lets wait to see what he says

**Comment by bfalacerda** [comment]
i haven't tested the last two commits, that's why i didnt merge it beforehand. Once I do we can merge this, and then #193. If you give me the go ahead on merging after testing I can take care of both @marc-hanheide

**Comment by marc-hanheide** [comment]
OK, @bfalacerda please take care of this, I'm a bit lost here...

**Comment by bfalacerda** [comment]
closing, #195 subsumes this

**Pull request closed without merging**
