### PR TITLE
Now using the new updateNamed method to ensure we don't get lots of maps...

### PR DESCRIPTION
**Pull request by hawesie**
... in the database.

### CODE REVIEW

**Comment by hawesie** [comment]
https://github.com/strands-project/ros_datacentre/pull/20 must be merged before this will compile.

**Comment by bfalacerda** [comment]
I merged both this and https://github.com/strands-project/ros_datacentre/pull/20, and I get the following error when I try to compile:

```
Linking CXX executable /home/strands/devel_ws/devel/lib/ros_datacentre_cpp_client/example_ros_datacentre_cpp_client
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../lib/libmongoclient.a(log.o): undefined reference to symbol 'boost::filesystem2::detail::status_api(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::system::error_code&)'
/usr/bin/ld: note: 'boost::filesystem2::detail::status_api(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::system::error_code&)' is defined in DSO /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../lib/libboost_filesystem-mt.so so try adding it to the linker command line
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../lib/libboost_filesystem-mt.so: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
make[2]: *** [/home/strands/devel_ws/devel/lib/ros_datacentre_cpp_client/example_ros_datacentre_cpp_client] Error 1
make[1]: *** [ros_datacentre/ros_datacentre_cpp_client/CMakeFiles/example_ros_datacentre_cpp_client.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 55%] [ 56%] Generating C++ code from ros_datacentre/GetParam.srv
Generating C++ code from ros_datacentre/MongoUpdate.srv
[ 56%] Built target strands_webserver_generate_messages_cpp
[ 56%] Built target ros_datacentre_generate_messages_cpp
Linking CXX executable /home/strands/devel_ws/devel/lib/message_store_map_switcher/message_store_map_saver
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../lib/libmongoclient.a(log.o): undefined reference to symbol 'boost::filesystem2::detail::status_api(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::system::error_code&)'
/usr/bin/ld: note: 'boost::filesystem2::detail::status_api(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::system::error_code&)' is defined in DSO /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../lib/libboost_filesystem-mt.so so try adding it to the linker command line
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../lib/libboost_filesystem-mt.so: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
make[2]: *** [/home/strands/devel_ws/devel/lib/message_store_map_switcher/message_store_map_saver] Error 1
make[1]: *** [strands_navigation/message_store_map_switcher/CMakeFiles/message_store_map_saver.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by hawesie** [comment]
A quick google suggest that we should swap

target_link_libraries(example_ros_datacentre_cpp_client
  ${catkin_LIBRARIES}
  ${Boost_LIBRARIES}
  mongoclient
)

for 

target_link_libraries(example_ros_datacentre_cpp_client
 mongoclient 
 ${catkin_LIBRARIES}
  ${Boost_LIBRARIES}
)

In CMakeLists.txt for example_ros_datacentre_cpp_client and message_store_map_saver. I don’t have this error, so can you try it for me?

**Comment by bfalacerda** [comment]
it works

**Comment by hawesie** [comment]
Can you make the fix after you've merged the PR? I'm a bit stuck for time today.

**Comment by bfalacerda** [comment]
i just merged from my fork as it was already fixed there. Closing this one

**Pull request closed without merging**
