### PR TITLE
adding new action to move_base type actions and making it a param

### PR DESCRIPTION
**Pull request by Jailander**
as needed by HAN https://github.com/strands-project/strands_hri/pull/148

### CODE REVIEW

**Comment by Jailander** [comment]
@marc-hanheide did it failed because of this: `d64.deb': No space left on device` ?

**Comment by marc-hanheide** [comment]
retest this please

**Comment by Jailander** [comment]
please don't merge last commit is untested

**Comment by Jailander** [comment]
now its tested will wait for tests at AAF by @gestom

**Comment by Jailander** [comment]
This has been tested on Werner and works, will merge

**Pull request merged**
