### PR TITLE
making sure topological navigation fails when it should

### PR DESCRIPTION
**Pull request by Jailander**
solves #281 partially needs testing with wheelchair scenario

### CODE REVIEW

**Comment by Jailander** [comment]
tested with wheelchair and human in endpoint seems to work

**Comment by marc-hanheide** [comment]
So... the failed test is expected? Then the test outcome needs to be changed, right @cdondrup ?

**Comment by marc-hanheide** [comment]
ah, I guess this also needs retesting with the new morse...

**Comment by marc-hanheide** [comment]
retest this please

**Comment by cdondrup** [comment]
Indeed, these test only pass if navigation to the end point is unsuccessful but the robot is able to go back to the starting point. I will add a field to the service reply to determine if the navigation timed out or if it failed on its own. Then these tests will only pass if navigation to the end point failed on its own account and if the robot is able to get itself free and return to the start point.

**Pull request merged**
