### PR TITLE
Logging trigger using white_list of nodes

### PR DESCRIPTION
**Pull request by cdondrup**
This node takes a list of topological nodes, to determine if the robot is allowed to log data. Useful for AAF.

Please see README for description of how it works.

### CODE REVIEW

**Comment by cdondrup** [comment]
Known issues:

If the robot leaves the node via normal move_base (no topo nav) it will report false, even though it might be in an area where it is allowed to record. This could be solved by listening to `/closest_node`  but this would introduce more leeway for errors. Since we are exclusively using topo nav, I don't think that would be a problem. Maybe @marc-hanheide has an opinion on that?

**Comment by marc-hanheide** [comment]
Why would it be more risky... In my head the solution was based on listening on /closest_node...

**Comment by cdondrup** [comment]
Using the current map, it wouldn't be I think.
The main problem is sending the robot to a place without a node that is in an area where we are not allowed to film but which is close to an allowed node. So if we would not have nodes in the east wing, then the closest node would be in the west wing and therefore we would still film, if that makes sense.

With the current map, this shouldn't happen though. Thing is, are we ever not using topo nav?
I can of course add the closest node easily.

**Comment by marc-hanheide** [comment]
We will probably only _not_ use topo nav for some tiny movement to orient towards the human. So, not travel massive differences. But I would prefer this to be based on passive observation, no matter how we are moving... But I also see your point. But loosing recordings, because we slightly move towards the interacting humans would be a problem. Hence, I think we should be using `clostest_node`

**Comment by cdondrup** [comment]
Also if I use the closest node, the boundaries would be a bit more fuzzy. If I send it to an allowed node and from there to a neighbouring forbidden one, it would only stop filming after traversing 51% of the edge. With the current implementation, it will stop immediately as the edge wouldn't be allowed.

**Comment by marc-hanheide** [comment]
I see the point... but I feel we might have move_base actions...

**Comment by cdondrup** [comment]
Just changing the topic from `/current_node` to `/closest_node`, achieves the wanted behaviour. I think just using that in the launch file as a default, should be fine?!
I'll do that and commit this asap.

**Comment by cdondrup** [comment]
OK, here is how it works now:

With the parameter `use_closest_node` set to `true` (default) it takes the closest node and as long as that is in the white list it will publish `true`. If started with `use_closest_node:=false`, only when being exactly on the node, it will publish true.

Hope that is alright @marc-hanheide, tested in simulation. Will test on the robot now.

The default behaviour is now that, as long as a white list node is close it publishes true regardless if topo nav is used or not.

**Comment by cdondrup** [comment]
Tried it on the robot, works a s intended. Tried it together with new logging component for head_xtion and upper body detector.

**Pull request merged**
