### PR TITLE
enable edge_reconfig for execute_policy_mode server

### PR DESCRIPTION
**Pull request by gpdas**
1. edge reconfig ported from topological_navigation/navigation.py (#374 )

When this mode is enabled via the `/topological_navigation/execute_policy_mode/reconfigure_edges` parameter, `execute_navigation_mode` action server will change edge action parameters (e.g. `move_base/DWAPlannerROS`) according to the `/edge_nav_reconfig_groups` parameter's values and edges being navigated, an example of this configuration is as follows:

```
edge_nav_reconfig_groups:
  irn:
    edges:
      - WayPoint1_WayPoint2
      - WayPoint2_WayPoint3
      - WayPoint3_WayPoint4
    parameters:
      - &id001
        name: forward_point_distance
        ns: move_base/DWAPlannerROS
        type: double
        value: 0.48297542551971
  orn:
    edges:
      - WayPoint66_WayPoint57
      - WayPoint57_WayPoint66
    parameters:
      - *id001
  utn:
    edges:
      - WayPoint46_WayPoint47
    parameters:
      - name: forward_point_distance
        ns: move_base/DWAPlannerROS
        type: double
        value: 0.1402690117118645
```

2. minor fixes in
  - topological_navigation/navigation.py
  - topological_navigation/route_search.py

### CODE REVIEW

**Comment by gpdas** [comment]
[Commit ac4c403](https://github.com/strands-project/strands_navigation/pull/376/commits/ac4c403fabbeaabc25cd9304fc6855245a0541bc) fixes #355

**Comment by gpdas** [comment]
```
18:59:42 Traceback (most recent call last):
18:59:42   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 235, in resolve_names
18:59:42     rosdep_key, view, installer, os_name, os_code_name)
18:59:42   File "/usr/lib/python3/dist-packages/rosdep2/catkin_support.py", line 87, in resolve_for_os
18:59:42     d = view.lookup(rosdep_key)
18:59:42   File "/usr/lib/python3/dist-packages/rosdep2/lookup.py", line 197, in lookup
18:59:42     return self.rosdep_defs[rosdep_name]
18:59:42 KeyError: 'message_store_map_switcher'
```

**Comment by gpdas** [comment]
@Jailander can you have a look at this please?

**Comment by Jailander** [comment]
Hi, I am happy with these, I tested them briefly didn't seem to break anything, but @bfalacerda maybe you want to double check this one before I merge?

**Comment by bfalacerda** [comment]
i can give it a quick test tmrw afternoon

**Comment by Jailander** [comment]
thanks!!!

**Comment by bfalacerda** [comment]
I didn't test the functionalities introduced by this PR but it doesn't break our setup, so happy for it to be merged

**Comment by Jailander** [comment]
:) thanks !! Will merge

**Comment by gpdas** [comment]
Thanks

**Pull request merged**
