### PR TITLE
Printing debug info and attempt to fix eternal retry problem

### PR DESCRIPTION
**Pull request by Jailander**
Printing debug info and attempt to fix eternal retry problem

### CODE REVIEW

**Comment by hawesie** [comment]
@bfalacerda please check through this

**Comment by bfalacerda** [comment]
looks good for testing in betty. @Jailander while you're at it, can you remove some of the output from door and edge prediction so the debug code you added here doesn't get lost in all the spam?

**Comment by Jailander** [comment]
@bfalacerda door prediction has very little prints already, did you mean something different?

**Comment by bfalacerda** [comment]
door and edge. at least edge prints values for all edges whenever it's called, which for the topo map in TSC  is quite a lot of lines

**Comment by bfalacerda** [comment]
oh i see you already committed something. That should be enough then :)

**Comment by Jailander** [comment]
Ok, its just that I had already removed most prints from door prediction, this should be a lot less spam on the edge side anyway

**Pull request merged**
