### PR TITLE
Safety stop

### PR DESCRIPTION
**Pull request by Jailander**
tidying up, making sure that navigation goals and free run policy is followed during safety stop and cancelling move_base too

### CODE REVIEW

**Comment by marc-hanheide** [comment]
Is this the fix for the latest problems we've seen in the test or is that still missing?

**Comment by Jailander** [comment]
Well that is the fix that is working in Linda but not in Werner, I'm still puzzled by that but should be merged anyway

**Comment by marc-hanheide** [comment]
a non-working safety stop is quite a bummer... it's a safety feature after all. I think we ought to give that another test on Monday, I'm afraid. Or @cdondrup

**Comment by cdondrup** [comment]
Yes, let's investigate properly on Monday.

**Comment by Jailander** [comment]
Yes, I would have tested it more properly in henry on Friday but since there was no one physically with tge robot it was impossible to test all I can say is that this is working smoothly on Linda and we can try again on Monday on Werner but its quite a useless test without anyone there to corroborate that the robot is on free run

**Comment by marc-hanheide** [comment]
status of this?

**Comment by Jailander** [comment]
As I said, its working properly in Linda and has been running on Werner since, however no one has used the emergency stop and no tests have been made

**Comment by marc-hanheide** [comment]
So we should try on Werner tomorrow.

**Pull request merged**
