### PR TITLE
fixing bug with repeated edges in prediction ...

### PR DESCRIPTION
**Pull request by Jailander**
... and adding test for this case in test top prediction

### CODE REVIEW

**Comment by Jailander** [comment]
@bfalacerda running `rosrun topological_navigation test_top_pred.py 100` will test the prediction you can see if there is a repeated edge in this line:

```
set of repeated edges:
set([])
```

**Comment by marc-hanheide** [comment]
@bfalacerda did you check this?

**Comment by bfalacerda** [comment]
will do tomorrow once we have internet

**Comment by marc-hanheide** [comment]
got internet today?

**Comment by RaresAmbrus** [comment]
Working on it. Should be done in another hour.

**Comment by Jailander** [comment]
I've tested it repeatedly today haven't seen it happen will keep testing

**Comment by RaresAmbrus** [comment]
And we've got internet!

**Comment by Jailander** [comment]
ooops, I made a big mess here mixing PRs I'll close this PR and the original PR will be in #233 sorry for the mess @marc-hanheide @bfalacerda

**Pull request closed without merging**
