### PR TITLE
Adding first version of topological test scenarios

### PR DESCRIPTION
**Pull request by cdondrup**
This adds quite a lot of things but for now I am mainly interested if this works on Jenkins. I will provide a more extensive explanation of the functionality tomorrow when I have more time so no merge yet, please.

This assumes that #276 has been merged as it rebased on top of it. 

Now let's see if Jenkins likes this or not.

**Edit:**

For description of functionality see the [README](https://github.com/cdondrup/strands_navigation/blob/test_scenarios/topological_navigation/tests/README.md)

Description of changes in this PR:
- Adding tests for topological navigation, currently only supported in simulation but real robot infrastructure to follow.
- Changing the functionality of `load_yaml_map.py`:
  - Uses argparse now, run `rosrun topologcial_utils load_yaml_map.py -h` for more information
  - Loads all the maps from a given directory or the map specified via its full path
  - Ability to change the name of the map using `--pointset NAME`. For inserting a single map, this name will be used as the topological map name. When inserting several maps from a direcoty they will use the given name + and index
  - Using `-f` overrides an existing map with the same name by deleting it first and then inserting the new map.
  - Running it with `--keep-alive` will not kill the node once the map/s are inserted but keep it alive and publish the service `/load_yaml_map/loaded` once the maps have been inserted. This can be used to run the script in a launch file and have other processes wait for the maps to be inserted before trying to access them.
  - The functionality is now in topological_navigation but the script calling it is still in `topological_utils`. This was necessary as the `scenario_server` for the tests uses the functionality and would have created circular dependencies otherwise.
- Exposing the number of retries before topological_navigation and execute_policy fail via the launch files:
  - `topological_navigation_retries`: default = 3
  - `execute_policy_retries`: default = 3
- Adding missing dependencies to monitored navigation

### CODE REVIEW

**Comment by Jailander** [comment]
Latest commit #276 fixes the 50 seconds thing and makes it a permanent fix

**Comment by cdondrup** [comment]
Most probably monitored navigation missing as a run dependency.

**Comment by cdondrup** [comment]
```
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/pr-indigo-strands_navigation/monitored_vcs/monitored_navigation/scripts/monitored_nav.py", line 9, in <module>
    from monitored_navigation.navigation import HighLevelNav
  File "/tmp/test_repositories/build_repository/devel/lib/python2.7/dist-packages/monitored_navigation/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 3, in <module>
  File "/var/lib/jenkins/workspace/pr-indigo-strands_navigation/monitored_vcs/monitored_navigation/src/monitored_navigation/recover_state.py", line 3, in <module>
    from mongo_logger import MonitoredNavEventClass
  File "/var/lib/jenkins/workspace/pr-indigo-strands_navigation/monitored_vcs/monitored_navigation/src/monitored_navigation/mongo_logger.py", line 5, in <module>
    from  movebase_state_service.srv import MovebaseStateService, MovebaseStateServiceRequest
ImportError: No module named movebase_state_service.srv
```

Monitored navigation itself seems to be miss dependencies like `movebase_state_service`. I'll fix that and try again.

**Comment by cdondrup** [comment]
@marc-hanheide 

```
[ERROR] [WallTime: 1446818005.352537] Fri Nov  6 13:53:25.352 [initandlisten] ERROR: Insufficient free space for journal files
[ERROR] [WallTime: 1446818005.360114] MongoDB process stopped!
[ERROR] [WallTime: 1446818005.360300] Mongo process error! Exit code=100
```

Not enough space on the disk?

**Comment by marc-hanheide** [comment]
yes :-( The problem are the massive journal files. I changed that in https://github.com/strands-project/mongodb_store/pull/153 but the currently released mongodb_store still has that problem... Annyoing. I'm waiting for @hawesie to allow me to merge https://github.com/strands-project/mongodb_store/pull/155 and re-release.

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
I increased the virtual disk file size a bit more... But the correct solution is to release https://github.com/strands-project/mongodb_store/pull/153

**Comment by marc-hanheide** [comment]
Ah, bugger, jenkins despatched the new test on a different client that does not have an increased file system yet... so, expect it to fail again...

**Comment by cdondrup** [comment]
OK, thanks for clarifying!

**Comment by marc-hanheide** [comment]
Hey, it worked!

**Comment by marc-hanheide** [comment]
nice video at https://lcas.lincoln.ac.uk/jenkins/job/pr-indigo-strands_navigation/114/artifact/Xvnc.mp4

**Comment by cdondrup** [comment]
Nice! Of course half of them failed due to wrong parameters but it ran successfully :)

**Comment by cdondrup** [comment]
This should be ready to merge now. The tests obviously fail because it does not pass them all but they run and produce a nice video of it.

Currently working on getting this to run on the real robot but will do this in separate branch and add to this PR or open a new if this has already been merged.

**Comment by Jailander** [comment]
Ok, I've seen them working, I'll merge

**Comment by marc-hanheide** [comment]
I'm reluctant to merge PRs that fail tests. I suggest to have two test files. one with only tests in it we expect to succeed and that one actually triggered in `CMakeLists.txt` and another full blown version including all tests, but not run automatically.

**Comment by marc-hanheide** [comment]
noooo, @jailander

**Comment by Jailander** [comment]
oops

**Comment by Jailander** [comment]
Shall I revert it?

**Comment by marc-hanheide** [comment]
I'd strongly advice so, yes. I renders the idea of PRs void if we accept failing tests. In many repos I have even disabled merging failing PRs. This should be the default.

**Comment by Jailander** [comment]
Ok I reverted it, but if we don't merge it people will have to pull from Christians branch to run the tests to tune the parameters

**Comment by Jailander** [comment]
@cdondrup is opening a new PR

**Comment by cdondrup** [comment]
I'll re-open it. 
Regarding the failing tests however, I am not sure we will ever find a set of parameters that will enable it to pass all the tests. Is there a way of defining system critical tests, like the programme not starting or the robot not moving at all and less critical ones like not being able to traverse a very narrow door?

**Comment by cdondrup** [comment]
Cannot, re-open. It tells me there is nothing to compare even though it has been reverted...

**Comment by marc-hanheide** [comment]
now @cdondrup can open another PR with your test, please? Please one that disables tests we know won't pass. 
You can't assign "criticality" to tests, but only "critical" test should be run as part of `CMakeLists.txt`, while other are run _on-demand_ via `rostest <package> <testfile>`, I suggest.

**Comment by cdondrup** [comment]
Just read @marc-hanheide comment... That sounds reasonable about splitting the test files. We just have to agree which tests the robot should always pass then. Maybe @jailander can compose a short list based on the current mb_test meaps.

**Comment by marc-hanheide** [comment]
@cdondrup you would have to rebase your branch, I think, and re-introduce your changes.

**Comment by marc-hanheide** [comment]
See: the branch is even protected. @Jailander did github not warn you about merging this? Maybe it didn't because I didn't check the checks that needs passing. Should do so now. We can even prevent admins from merging failed PRs.

image

**Comment by Jailander** [comment]
no it did not warn me, everything was as usual.

**Comment by marc-hanheide** [comment]
should now...

**Comment by cdondrup** [comment]
I cannot open a new PR. Even after a rebase of my branch onto the current indigo-devel it tells me that there is nothing to compare. This kind of makes sense because the exact same commits have been merged and then reverted which means that even with a rebase it doesn't turn them into new commits.

I see 3 possible solutions:
1. we revert the revert
2. we forcefully reset the state of strands_navigation to a commit before my changes
3. something @marc-hanheide comes up with that is a bit nicer ;)

Edit: after reverting the revert I will commit a new PR that separates out the non-critical tests.

**Comment by cdondrup** [comment]
OK, I can apparently cherry-pick all the commits I need onto the current version of strands_navigation... might take a few minutes but I'll try that.

**Pull request merged**
