### PR TITLE
Re-opening #277 - topo nav testing

### PR DESCRIPTION
**Pull request by cdondrup**
I addition to what was described in #277 this PR also splits the tests into critical and supplementary tests. The critical tests (currently only one: going around a corner in a 2m wide corridor) are run on jenkins. The supplementary tests can be run locally to check parameter sets. See [README](https://github.com/cdondrup/strands_navigation/blob/b256a867cea185ba0b16a4a8893566f412cf49e4/topological_navigation/tests/README.md) for details.

### CODE REVIEW

**Comment by cdondrup** [comment]
Passed: https://lcas.lincoln.ac.uk/jenkins/job/pr-indigo-strands_navigation/lastSuccessfulBuild/artifact/Xvnc.mp4

More critical tests can be added later on by just adding them to https://github.com/cdondrup/strands_navigation/blob/test_scenarios2/topological_navigation/tests/topological_navigation_tester_critical.py

**Comment by cdondrup** [comment]
Adding real world robot tests for static scenarios. See README in `topological_navigation/tests` for explanation.

This also adds a joypad control to toggle between start and reset. Functionality described in README.

**Comment by cdondrup** [comment]
Tests have passed, please merged once approved by @Jailander and @marc-hanheide.

**Comment by Jailander** [comment]
I will wait for @marc-hanheide this time ;)

**Pull request merged**
