### PR TITLE
Creating topological map image at predicted time

### PR DESCRIPTION
**Pull request by Jailander**
running `rosrun topological_utils draw_predicted_map.py` will create a png of the predicted map like the one below in the current folder for the current moment.

predmap

Red circles are the nodes are the blue arrows are the edges (the wider the higher probability of success at the given time)
For drawing the predicted time for specific epochs do `rosrun topological_utils draw_predicted_map.py epoch(in seconds)`.
you need to have a map and topological map being published on the `/map` and `/topological_map` topics and topological prediction running (of course navstatistic for that topological map are prefered) 
there is a convenience launch file to test this: `roslaunch topological_navigation topological_map_visualise.launch map:=/path/to/test_slam_map.yaml pointset:=test_topological_map`

### CODE REVIEW

**Comment by marc-hanheide** [comment]
I suppose this is not the data from a real run in the image? Also, if you publish this annotated image on a topic, and read the epoch from another topic, we could easily create a video out of this that shows the progression through time. Just an idea. 
One last thing: What about the traversal times? Could it be an idea to have another mode where the width changes according to time? You mentioned to encode that in the colour, but my feeling is that could get a little tricky to see, or an alternative solution: Encode the probability in saturation of the edge (from white to blue), so that 1.0 is full blue. and the "velocity" (distance/ predicted time) in the width. Then reliable, fast edges stand out, and they are normalised for distance. What do you think?

**Comment by marc-hanheide** [comment]
Oh, great stuff BTW ;-)

**Comment by Jailander** [comment]
Yes this is data from a simulated run that I did, I was silly enough to not use real which I could perfectly had :/ I'll do so tomorrow if I still have access to henry. 
This is just the first version, I'm already working on the traversal times, funny enough I was already working on it the way you are sugesting, but I wanted @hawesie to see it now to get his thoughts too. 
About the video Idea, I had it already in mind, my plans were to have that possibilty on this script telling it to create a video between two epochs (I also wanted to add the time in human readable format to it), I think this could be easier. I would use the topic idea for updating the Rviz markersthat we've talked about

**Comment by hawesie** [comment]
It looks good. It might be nice to also do this only for a subset of nodes with the image being appropriately cropped.

**Comment by Jailander** [comment]
That's a good idea, I'll add it to my list

**Comment by hawesie** [comment]
Also, related to the testing I'd like to do, it would be good to constrain the date range of the nav stats used to build the underlying fremen model. Is this possible?

**Comment by Jailander** [comment]
Not right now, but I can do it, I'll create an issue for this.

**Comment by hawesie** [comment]
If you do that, I might be able to do the work for it.

**Comment by Jailander** [comment]
Sorry you lost me in there, Do you want to do it yourself? I really don't mind doing it, it shouldn't take long

**Comment by hawesie** [comment]
I don't mind. I'd like this functionality available on Saturday when I plan to start looking at data. If you can do if before then that would be great, else I can do it.

**Comment by Jailander** [comment]
I'll do it today

**Comment by hawesie** [comment]
Cool, thanks!

**Pull request merged**
