### PR TITLE
streamlining nav pipeline

### PR DESCRIPTION
**Pull request by bfalacerda**
this makes the execution of navigation policies less buggy

### CODE REVIEW

**Comment by cdondrup** [comment]
Does anyone with a working robot volunteer to test this? Quite substantial changes from the looks of it.

**Comment by Jailander** [comment]
It was working on Linda last week and it does in simulation, however, it should be tested somewhere else since sensitive changes to monitored navigation have been made @BFALacerda any plans on testing it on any of your two fancy robots?

**Comment by bfalacerda** [comment]
Not until next week...

What I'd like to test is the whole integrated system, with a routine running. If anyone has a routine ready for their environment, it's just running that. We need to add the new policy execution node to a launch file though, maybe just put it in the current topological_navigation.launch?

**Comment by Jailander** [comment]
Ok I just added it to the launch file @BFALacerda you will need to pull into your repo like last commit,  we can't test anything as Linda is down https://github.com/strands-project/scitos_robot/issues/60 :( maybe somebody else can volunteer I'm mentioning @nilsbore and @RaresAmbrus just to annoy them

**Comment by bfalacerda** [comment]
I just added the new monitor_navigation stuff here, I forgot that the stuff I did in Lincoln wasn't tested... Anyway, I tested it quite a lot here and everything was working.

There a build fail, how do I check what happened, the logs are messy and I don't know where to look at...

**Comment by hawesie** [comment]
Failed log is https://lcas.lincoln.ac.uk/jenkins/job/pr-hydro-strands_navigation/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=devel/lastBuild/console if that helps. =

**Comment by bfalacerda** [comment]
I'm pretty lost with this...

jenkins is still complaining about mongodb_store_cpp_client but I don't see it anywhere else...
It's also complaining about visualization_msgs on topological_utils for some reason @Jailander

**Comment by Jailander** [comment]
I requested a pull in #89 including visualization_msgs in package xml to see if this deals with the warning message

**Comment by bfalacerda** [comment]
I included #89 here so it can be closed.

**Comment by Jailander** [comment]
thanks :D

**Comment by bfalacerda** [comment]
This is weird, it looks like jenkins is always testing the second to last commit and not the last one. 

The test was run for my latest commit (see above the green tick) but then if i click the link I got in the email saying the build is back to normal:

https://lcas.lincoln.ac.uk/jenkins/job/pr-hydro-strands_navigation/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=devel/12/changes

It shows the other 2 commits me and Jaime did before as the changes being tested. My latest change has nothing to due with the visualization_msgs issue that was creating the error.

If I click the green tick everything looks normal though:

https://lcas.lincoln.ac.uk/jenkins/job/pr-hydro-strands_navigation/12/

I'm really confused about this, is there a Jenkins for dummies tutorial somewhere?

**Comment by marc-hanheide** [comment]
The changes it displays are indeed incorrect (that's a nuisance but not a problem). But the build is actually correct. Congrats. You made it work

**Comment by marc-hanheide** [comment]
Also... It's all consistent IMO. The build for the green tick succeeded so what's your problem?

**Comment by marc-hanheide** [comment]
One comment: you want to sanity check install targets and emails before releasing. Also make sure that all package.xmls list all dependencies for each individual package.

**Comment by bfalacerda** [comment]
It should have succeeded when @Jailander did his changes:

https://github.com/BFALacerda/strands_navigation/commit/32fcf35e9d0bc2016fc26207bdd03e0c149a0490

What I did in https://github.com/BFALacerda/strands_navigation/commit/9ef9ee428e835c7b0065ead5b6247cb48e372d67 (the commit where it finally succeeded) didn't have anything to do with the compilation issues. I think that's why I also saw it complaining about mongodb_store_cpp_client after all references to it were commented out. It only stopped complaining only _after_ the next commit.

**Comment by marc-hanheide** [comment]
Then your branch wasn't in sync with upstream I suppose. I can't see why it
should do it otherwise. It works everywhere else. Of course I'm not fully
ruling out any bugs but from what I can see it checked out the right
version. Just the changes that are reported are not always correct I think.

**Comment by bfalacerda** [comment]
It might be that, I did have some syncing issues. I don't know why this one would fail though, here everything was synced:

https://github.com/BFALacerda/strands_navigation/commit/a3fa22843309aff908fd261f22afe7877bd6e518

Anyway, it might have been me messing up, so let's hope it was :)

**Comment by marc-hanheide** [comment]
Exactly... Let's celebrate that it succeeds now 😋

**Comment by hawesie** [comment]
I thought I was seeing this too on https://github.com/strands-project/strands_executive/pull/85 as the current fail should've gone away. I do have other errors there though, so I'll keep plugging away.

**Comment by marc-hanheide** [comment]
OK... Now I'm curious. Keep me posted if you see this again. I tested it
with a PR and it worked.  Jenkins is not doing any magic there. It simply
checks out the pull request as it is provided by github. I can't see how it
would manage to take the wrong one there. But let's see again.

**Pull request merged**
