### PR TITLE
adding topological map publisher and adapting localisation node

### PR DESCRIPTION
**Pull request by Jailander**
and others like adding scripts to topological utils

### CODE REVIEW

**Comment by hawesie** [comment]
Please can someone run this and let me know if it works? I'm starting to really think we need a set of tests which can be passed before merging.

**Comment by Jailander** [comment]
I have tested it and it works, however I haven't tested it together with the scheduler, I can try it tomorrow and tell you for sure. Only the last two commits on this pull request can create conflicts on the system.

**Comment by hawesie** [comment]
I was looking for a non-author tester really.

**Comment by Jailander** [comment]
Ok, in any case I will test it tomorrow on Linda with the scheduler and tell you

**Comment by cdondrup** [comment]
Just tested it. Most of the added functionalities seem to work but it still showed some bugs:
- After a waypoint was updated you sometimes have to relaunch the visualisation in order to use the goto markers
- There seem to be double the number of interactive markers for the verts (2 on top of each other for every vert) and the edge markers for the influence zone alternate between the two sets of verts.

Minor issue:
- Old edges are not removed if a waypoint is moved. New edges are added on top of the old ones. This is purely a visualisation problem because subscribing and unsubscribing from the edges topic clears these markers. Specifying a marker lifetime might help.

Also, could you please add a readme describing all these nice functionalities? I for example wasn't able to use it without asking you personally @Jailander 

This PR needs: https://github.com/strands-project/strands_msgs/pull/24 merged!

**Comment by Jailander** [comment]
So @cdondrup I think last commit fixes most issues, maybe you can merge or even better wait until I add some new untested functionalities and have more testing on this thread before we actually merge it. Also I won't write the readme until I finish the other functionalities

**Comment by cdondrup** [comment]
As I tested this a long time ago and it worked, I'll finally merge it so Jaime and Bruno can work on it.

**Pull request merged**
