### PR TITLE
Part 2 of moving topological navigation packages to …

### PR DESCRIPTION
**Pull request by Jailander**
… https://github.com/LCAS/topological_navigation

### CODE REVIEW

**Comment by marc-hanheide** [comment]
this is likely not working until we have released topological_navigation packages form the the other repo, so I'll defer this one.

**Comment by marc-hanheide** [comment]
retest this please

**Review by marc-hanheide — APPROVED** [review]
even the test build worked, so good.

**Comment by Jailander** [comment]
Oh cool!

**Comment by hawesie** [comment]
I think I missed Part 1. What’s the plan here?

**Comment by Jailander** [comment]
Hi Nick, Sorry we should have opened a discussion about this, I am going to be updating topological navigation in the next couple of weeks, the idea is to make it a bit more flexible, improve usability and  some code cleanup. To do this we moved some packages to https://github.com/LCAS/topological_navigation 

Here is a (non full) list of different things we are trying to add:
* To have the ability to have any type of action connecting the nodes, not only actions that have `move_base` goal type.
* The parameter set for each action can be defined on the edge(s) as necessary (as long as they can be dynamically reconfigured). This is mainly to remove the messy `reconfigure_edges` system and have it fully integrated in topological navigation.
* Have a simplified map manager version that runs only from the map file.
* Have the ability to change failure policy on a per node basis. Instead of having one general param for the number of retries, you can define a policy per node, telling it to either **retry** (for number of times and after a determinate amount of time), **re-plan** or **fail**. or a combination of those, for example, **retry twice**, then **re-plan**, then **fail**.
* The topological map will have its own frame, so if an area is remapped from a different origin you only need to change the transformation between the *map* frame and the *topological map* frame instead of having to change the whole topological map.
* ***_All these changes should be backwards compatible_***.

Any suggestion and ideas are welcome!!

**Comment by marc-hanheide** [comment]
In particular, in terms of released packages nothing is going to changes. This is just moving topo-nav into different repository, to free it of some legacy, and making it easier to manage as a stand-alone repo.

**Comment by hawesie** [comment]
+1 for stability and long-term strategy!

**Comment by marc-hanheide** [comment]
and once this is done, I'm happy to move this into official ROS repos, too.

**Comment by heuristicus** [comment]
Is the plan to have topological rviz tools in the new location as well?

**Pull request merged**
