### PR TITLE
[topological_navigation] Added the wait_reset_bumper_duration arg to top_nav.launch

### PR DESCRIPTION
**Pull request by nilsbore**
This just adds the parameter in https://github.com/strands-project/strands_recovery_behaviours/pull/55 to allow us to set it from the bringup. Allows to specify the wait time before continuing after the bumper has been released without human help.

### CODE REVIEW

**Comment by nilsbore** [comment]
@Jailander please have a look.

**Comment by Jailander** [comment]
looks fine, have you tested it on rosie? I'll test in Linda anyway before merging

**Comment by nilsbore** [comment]
Yes, it's working fine on Rosie.

**Comment by Jailander** [comment]
Tested in Linda :+1:

**Pull request merged**
