### PR TITLE
WIP: topo2svg

### PR DESCRIPTION
**Pull request by marc-hanheide**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
This is to implement a topological map to SVG visualisation. Already does some decent job:

image

Eventually, it shall also listen on the `/topological_map` topic and publish the XML SVG format automatically. For now, works with files, maybe interesting to @Jailander

**Comment by Jailander** [comment]
Wow!! That is great and useful :) will check it out briefly

**Comment by Jailander** [comment]
I know its still in development ;) but tried it, and found these issues:
* `topo2svg.py` is not executable 
* `svgwrite` module needs to be installed
also I see still doesn't load topo map ping if you need me to test later or if you want some help :)

**Comment by hawesie** [comment]
Is this still live?

**Comment by marc-hanheide** [comment]
I wish it were :-) It would certainly be useful but never got finalised. But, I'm sure, @Jailander this would be useful for Ioannis to adopt it for TOC or similar? Definitely, don't kill the branch, but this should now go into https://github.com/LCAS/topological_navigation

**Comment by Jailander** [comment]
Hi, 

Yes that is a good idea, I will find some Saga resources to throw at this.

**Pull request closed without merging**
