### PR TITLE
Adding waiting for the add_node service

### PR DESCRIPTION
**Pull request by mudrole1**
Without this wait, the code was sensitive in which order the nodes from launch files start, i.e. it worked only sometimes.

### CODE REVIEW

**Comment by mudrole1** [comment]
The change to "topological_map.py" is that there is no map to load after one is deleted (it was throwing exception)

**Comment by mudrole1** [comment]
"mapping.launch" fixed an obvious arg mistake

**Comment by hawesie** [comment]
Looks good to me. @heuristicus and @Jailander ok to merge?

**Review by heuristicus — COMMENTED** [review]
Yep, looks good to me too.

**Pull request merged**
