### PR TITLE
Fixes in topological utils

### LINKED ISSUE #266: [topological_navigation] map_publisher.py is not installed
Which is why the examples given in the README don't work with the installed version of topo nav.

### PR DESCRIPTION
**Pull request by Jailander**
Fixes #266 and #280

### CODE REVIEW

**Comment by cdondrup** [comment]
When launching `create_topological_map.launch`:

```
roslaunch file contains multiple nodes named [/topological_map_manager].
Please check all <node> 'name' attributes to make sure they are unique.
Also check that $(anon id) use different ids.
The traceback for the exception was written to the log file
```

Line 15 and 21 are duplicates.

`empty_topological_map.launch` seems to work fine.

The map export seems to be fixed now and works for me. It is a bit spammy now though:

```
cdondrup@calculon:~
$ rosrun topological_utils map_to_yaml.py mb_test16 bla.yaml
True
------------------


------------------


------------------
{'topic': '/battery_state', 'field': 'charging', 'val': True}
{"topic": "/battery_state", "field": "charging", "val": true}
------------------
{'topic': '/battery_state', 'field': 'charging', 'val': True}
{"topic": "/battery_state", "field": "charging", "val": true}
------------------
{'topic': '/battery_state', 'field': 'charging', 'val': True}
{"topic": "/battery_state", "field": "charging", "val": true}
------------------
{'topic': '/battery_state', 'field': 'charging', 'val': True}
{"topic": "/battery_state", "field": "charging", "val": true}
------------------


```

**Comment by Jailander** [comment]
ooops let me fix these two things it'll be a min (so like 15)

**Comment by Jailander** [comment]
it only took me 17 mins ;)

**Comment by cdondrup** [comment]
Looks good to me know. Thanks!

**Pull request merged**
