### PR TITLE
reconfiguring speed and removing move_base to closest node

### PR DESCRIPTION
**Pull request by Jailander**
This PR reconfigures speed depending on edges configurations and removes move_base to closest node when not at node, for reconfiguring speeds on human_aware_navigation edges  https://github.com/strands-project/strands_hri/issues/86 needs to be solved

### CODE REVIEW

**Comment by bfalacerda** [comment]
i just tested this, along with https://github.com/strands-project/strands_hri/pull/113 and https://github.com/strands-project/strands_systems/pull/110, but he still drives at 0.55 everywhere

**Comment by Jailander** [comment]
Yes there is still one more change needed will commit it asap

**Comment by Jailander** [comment]
Hi,
With this second part of the PR, some things have changed, basically now reconfiguring speeds and tolerances from topological navigation in move base type actions has to be handled by the action server itself:
For example if you are using `move_base` execute policy will reconfigure `/move_base/DWAPlannerROS` 
If you are using `human_aware_navigation` it will reconfigure `/human_aware_navigation/DWAPlannerROS` 
So if there is any other move base like action to be implemented it will need to include a reconfigure server called `/new_move_base_based_action_name/DWAPlannerROS`

**Comment by marc-hanheide** [comment]
retest this please

**Comment by Jailander** [comment]
Hi, @bfalacerda is this working on Bob? merge?

**Comment by bfalacerda** [comment]
i havent tested the full PR, just c3199771cb5fe962f186802579d83992a5172151

It reconfigures the speed for move base properly

**Comment by bfalacerda** [comment]
i'll add the rest of the PR now

**Comment by bfalacerda** [comment]
when with_human_aware is set to False of strands_navigation.launch, this gets stuck at

```
Creating Reconfigure Client /human_aware_navigation/DWAPlannerROS      
```

**Comment by cdondrup** [comment]
This is because dynamic reconfigure clients block. There is a timeout you can set, but: If human_aware is not launched but the edge uses it, the robot will not move anyway. If human_aware is not launched and the edge uses move_base, this shouldn't be called.

**Comment by bfalacerda** [comment]
i think we have the latter here: human_aware is not launched, all edges use move_base, but it still blocks there. maybe it tries to create a client at startup regardless?

I'll  almost sure we dont, but i'll confirm if  have any remaining human_aware_navigation edges

**Comment by cdondrup** [comment]
If you don't have any, then it shouldn't try to create a client. Otherwise, this will always block and it's not very legible behaviour to create a client to something that is not used.

**Comment by cdondrup** [comment]
As a hot fix: adding `timeout=5.0` to the dynamic_reconfigure.client constructor, throws and exception after 5 seconds and then continues if caught.

**Comment by bfalacerda** [comment]
confirmed that it only has move_base edges.

my hot fix was setting with_human_aware to True for now

**Comment by cdondrup** [comment]
Also works :)
But then @Jailander should have a look why it tries to create a human_Aware client if it is not used.

**Comment by Jailander** [comment]
yes I'll fix ASAP

**Comment by Jailander** [comment]
This last commit fixes that issue

**Comment by marc-hanheide** [comment]
I really hope you guys know what you're doing here. There are quite a few changes in the PR, I cannot assess this properly.

**Comment by Jailander** [comment]
I think this is the current running system on bob (is this right @bfalacerda ?) except for the last commit which will allow them at (g4s) not to run human_aware_navigation, I have tested it here and works.

**Comment by bfalacerda** [comment]
what is properly tested in bob is https://github.com/strands-project/strands_navigation/commit/c3199771cb5fe962f186802579d83992a5172151

i merged some more stuff yesterday, but now we're having some problems, let's wait for @kunzel to merge the whole thing and see how it goes. if it goes badly, maybe we should split the PR into two, merge everythin until  https://github.com/strands-project/strands_navigation/commit/c3199771cb5fe962f186802579d83992a5172151
, and do further robot (other than bob) testing

**Comment by Jailander** [comment]
retest this please

**Comment by Jailander** [comment]
@bfalacerda what do you say about this, I've tested in simulation and Linda and seems to be running on Bob now, right?

**Comment by bfalacerda** [comment]
I think @kunzel is running it on bob now, you'll have to ask him

**Comment by Jailander** [comment]
@Kunzel said: `@Jailander no i think it's fine. Thanks for the quick fix.` at 3:43 pm, but that was only for the dyt thing not sure about the rest

**Comment by kunzel** [comment]
yes this was for the `dyt`. What else could go wrong has changed?

**Comment by Jailander** [comment]
Nothing really, I think the goal now was to test it not running human_aware_navigation, if the speeds change outside of the corridor (I think). Then its fine

**Comment by bfalacerda** [comment]
the speed was cjhanging yesterday. you can do `rosparam get  /move_base/DWAPlannerROS/max_trans_vel` to see if it still is. It should be 0.55 in the corridor, 0.35 everywhere else.

I would say that if the robot spends the rest of the day going around, we can merge

**Comment by bfalacerda** [comment]
tested on bob

**Pull request merged**
