### PR TITLE
Add utility to check map for errors.

### PR DESCRIPTION
**Pull request by cburbridge**
This is a utility script that checks the map for simple errors:
- duplicate nodes
- duplicate edges
- dangling edges

### CODE REVIEW

**Comment by Jailander** [comment]
Did you check migrate.py does the same and fixes but might be messy by now

**Comment by cburbridge** [comment]
No idea about migrate.py, so wrote this. Looks like migrate does a lot more than just check and output some info. I prefer the small simple utilities approach, but feel free to delete this PR if it is not useful.

**Comment by Jailander** [comment]
No, I mean its fine, migrate.py was made to migrate from the older versions of the map to the current version, but it does check for errors and fixes them but I also like small utilities just telling you there was that option too. I can't check it now, but if it works for you merge it

**Comment by marc-hanheide** [comment]
as this just adds a new script, it's fine.

**Pull request merged**
