### PR TITLE
Smaller influence radii for ChargingPoint, Station

### PR DESCRIPTION
**Pull request by lucasb-eyer**
According to @BFALacera, these should be extremely small. Right now they are exactly twice the default size and thus include eachother.

### CODE REVIEW

**Comment by lucasb-eyer** [comment]
Don't merge yet, I still have to test it on the robot. Opened the PR for discussion and not to forget about it. @Jailander

**Comment by Jailander** [comment]
yes, I'm sorry I forgot to change that, yes, I think it is a bit too small, I'll take a look and if not I'll modify it using the one we have in Linda right now.

**Comment by Jailander** [comment]
that was a bit too small, I'll pull a better one closing this pull request now

**Comment by Jailander** [comment]
#124 does this too with slightly bigger influence areas

**Pull request closed without merging**
