### PR TITLE
[backtrack_behaviour] This implements the backtrack recovery as an action server

### PR DESCRIPTION
**Pull request by nilsbore**
This implements the backtrack recovery as an action server in a separate package. Maybe it should eventually be moved to scitos_2d_navigation but I'm leaving it here for now. One problem is that it is preempted when close to waypoints but this doesn't seem to lead to any other issues than that the recovery is not executed. If it goes further away from the start than the requested meter's back by planning some odd path, the action gets aborted. Tested this on Rosie but it is hard to see any gains in scenarios that are not staged by me.

### CODE REVIEW

**Comment by nilsbore** [comment]
An issue that I noticed is that the sensor sees right through glass so it planned a path into one of our glass doors. Are there any glass doors/walls at G4S?

**Comment by cdondrup** [comment]
@nilsbore this PR cannot be merged automatically. Can you please resolve these conflicts?
@BFALacerda I think you should test this since it changes stuff in the monitored navigation. But if I remember correctly you are on holiday. Is there anyone else who feels confident enough to check this? If there are no volunteers I will try to test it on Linda.

**Comment by bfalacerda** [comment]
I'm on holiday yes. From what I've seen, the changes in monitored nav are minor, it's just adding an extra state.

**Comment by cdondrup** [comment]
Thanks @BFALacerda , I'll test this as soon as @nilsbore resolves the conflicts (don't want to break anything by merging it myself) and after I've tested it on Linda.

**Comment by bfalacerda** [comment]
This can be closed, I added it to strands_recovery_behaviours

**Pull request closed without merging**
