### PR TITLE
Adding navigation tests using obstacles that are not in the SLAM map

### PR DESCRIPTION
**Pull request by cdondrup**
To allow for a more flexible static test set-up, this new functionality adds tests that use obstacles:
- a standing human model
- a wheelchair
- an office chair
- a regular chair

and adds them to the mba environment. This is achieved using the topological map. For a detailed description, see README file.

**Brief description:**
A node in the map called `ObstacleHumanStatic1` will add a standing human model with the given orientation and position to the environment before running the test. This way you can add obstacles that are not in the SLAM map. Decomposing the name, `Obstacle` is the prefix for obstacle nodes that can be defined in the `tests/conf/scenario_server.yaml` and `HumanStatic` is one of the obstacle types that is defined in the same file, the `1` is just to make the name unique. There are currently 10 instances of every object which can be used. The obstacle nodes should not have any edges and have to use localise by topic so the robot never localises at one of the nodes. See README for more details on how to create them.

Added tests:
- `mb_test11`: Wheelchair blocking an intermediate node in open space.
- `mb_test12`: Wheelchair blocking final node in open space. Graceful fail has to be tru to pass this test as the node itself can never be reached precisely.
- `mb_test13`: Human blocking an intermediate node in open space.
- `mb_test14`: Human blocking final node in open space. Graceful fail has to be tru to pass this test as the node itself can never be reached precisely.
- `mb_test15`: Non-SLAM map chairs on one side of 2m wide l-shaped corridor.
- `mb_test16`: Non-SLAM map wheelchairs on one side of 2m wide l-shaped corridor.
- `mb_test17`: Non-SLAM map wheelchairs block 2m wide l-shaped corridor after intermediate waypoint. Graceful fail has to be tru to pass this test as the node itself can never be reached.
- `mb_test18`: Non-SLAM map static humans block 2m wide l-shaped corridor after intermediate waypoint. Graceful fail has to be tru to pass this test as the node itself can never be reached.

All of these are run when  starting the supplementary test file.

**Bug fix**

The scenario server now actually waits for morse to report the result of moving the robot and or obstacles.

**Test results**

for some of the new tests where the final node is blocked or the way if cut off before reaching the final node, the test will pass when the robot fails gracefully, i.e. notices that it cannot reach and fails, then trying to go back to the start.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
so... is this expected to fail? Is it a test? What failed?

**Comment by marc-hanheide** [comment]
looking at [this](https://lcas.lincoln.ac.uk/jenkins/job/pr-indigo-strands_navigation/122/console) something went wrong in launching it, right?

```
Simulation <mba_test.py> not found! (I was looking for </opt/ros/indigo/share/strands_morse/mba/mba_test.py> or </var/lib/jenkins/.ros/mba_test.py>)
```

**Comment by Jailander** [comment]
True I am testing this and needed to pull this: https://github.com/strands-project/strands_morse/pull/145

**Comment by marc-hanheide** [comment]
right... I merged https://github.com/strands-project/strands_morse/pull/145 and triggered a release of strands_morse

**Comment by Jailander** [comment]
It works for me (after I pulled from strands morse)

**Comment by marc-hanheide** [comment]
let wait until it's re-released and test it again then.

**Comment by cdondrup** [comment]
Yes, it needs the new test environment from strands_morse. Forgot about that.

**Comment by marc-hanheide** [comment]
retest this please

**Pull request merged**
