### PR TITLE
Topmap editor

### PR DESCRIPTION
**Pull request by heuristicus**
See readme for details on what this does.

Requires #345

### CODE REVIEW

**Comment by marc-hanheide** [comment]
retest this please

**Comment by heuristicus** [comment]
I'm not sure why this is crashing. I've had it compile first try on at least 2 machines, and the file it's complaining about definitely exists.

**Comment by marc-hanheide** [comment]
Can you please rebase this on the latest main branch now that #345 is merged

**Comment by marc-hanheide** [comment]
Ignore me. That's not the problem

**Comment by marc-hanheide** [comment]
I think the problem is that AddEdge.h is a generated file and the srv generation didn't happen at this point. So, there is messing dependency of the file that uses it on the service code generation

**Comment by cdondrup** [comment]
I see there are some dependencies missing to make sure that the message builds first: http://answers.ros.org/question/188982/message-headers-wont-build-first/#189133 ;)

**Comment by heuristicus** [comment]
@cdondrup thanks - I just discovered that that is what was missing. I wasn't aware that that dependency existed.

**Comment by marc-hanheide** [comment]
yeah!

**Pull request merged**
