### PR TITLE
Topological prediction enhanced

### PR DESCRIPTION
**Pull request by Jailander**
Now the topological predictions use speeds for estimating traversal time, this is better as this value is normalised.

needs: https://github.com/strands-project/fremen/pull/20 to be merged

@bfalacerda can you check this please with strands_executive things?

### CODE REVIEW

**Comment by marc-hanheide** [comment]
I triggered a re-release of fremen with https://github.com/strands-project/fremen/pull/20 merged. Then this should be tested again.

**Comment by bfalacerda** [comment]
is there anything in particular I should worry about?
I assume that from the executive point of view nothing ha changed and it still needs to call the same service right?

**Comment by Jailander** [comment]
yes everything is the same, however, I'm unsure if times might be shorter now as we were using an scaling factor to make sure they were schedulable (how do you say that?) not a bit deal, but it would be nice to know.

**Comment by bfalacerda** [comment]
ok, i can try a simple routine and see if everything goes through but i dont have a more complicated one to test on atm

**Comment by Jailander** [comment]
yeah that's something we should work on, I have some ideas, after the predeployment in Vienna, I can set up a simulation and create some statistics for that simulation, having that making tests should be easy

**Comment by bfalacerda** [comment]
@Jailander I started strands_navigation and topological_prediction is running, but I don't see the `/topological_prediction/predict_edges` service. Any idea why?

**Comment by Jailander** [comment]
Hi, give it a minute is not published until all the stats have been gathered, I left it very spammy but it should say all done if you start topological prediction on its own terminal

**Comment by bfalacerda** [comment]
I ran it in another terminal and got the All done, but still no service.

I also tried without this PR and the service appears.

**Comment by Jailander** [comment]
ok that's weird :/ I'll check, can you run this `rosrun topological_navigation test_top_pred.py 1000` and tell me if it works please?

**Comment by bfalacerda** [comment]
Ah! sorry, I forgot to update fremen. Ignore everything. Thanks though :)

**Comment by Jailander** [comment]
haha good :D

**Comment by bfalacerda** [comment]
The expected times looks sensible, and I can run our basic patrolling routine normally.

**Comment by Jailander** [comment]
great!!!
:)

**Pull request merged**
