### PR TITLE
Map edition fixes

### PR DESCRIPTION
**Pull request by Jailander**
this fixes some minor bugs in map export, edition launch file and add edges service

### CODE REVIEW

**Comment by marc-hanheide** [comment]
tested?

**Comment by Jailander** [comment]
yes, and tests for this on the way

**Comment by marc-hanheide** [comment]
Which way? 😀

**Comment by Jailander** [comment]
haha, on their way still ... :P fixing somethings that need fixing

**Comment by marc-hanheide** [comment]
Does need urgent merging? Otherwise I'd wait until after LAMOR

**Comment by marc-hanheide** [comment]
@Jailander ?

**Comment by Jailander** [comment]
Well I was planning to add a couple more things to this PR as it was never merged, it works anyway and I haven't started working on them so merge if you want I'll make another PR  with th few changes I wanted to make.

**Pull request merged**
