### PR TITLE
Simulating policy execution better.

### PR DESCRIPTION
**Pull request by hawesie**
Updates required for testing new MDP executor.

### CODE REVIEW

**Comment by hawesie** [comment]
@marc-hanheide @Jailander disk space troubles?

```
I: Mounting /var/lib/jenkins/workspace/pr-indigo-strands_navigation
I: policy-rc.d already exists
I: copy /var/lib/jenkins/workspace/pr-indigo-strands_navigation/jenkins_scripts/devel to target directory
I: Obtaining the cached apt archive contents
cp: error writing '/var/cache/pbuilder/build//31985/var/cache/apt/archives/libkrb5-26-heimdal_1.6~git20120311.dfsg.1-2ubuntu0.1_amd64.deb': No space left on device
cp: failed to extend '/var/cache/pbuilder/build//31985/var/cache/apt/archives/libkrb5-26-heimdal_1.6~git20120311.dfsg.1-2ubuntu0.1_amd64.deb': No space left on device
cp: error writing '/var/cache/pbuilder/build//31985/var/cache/apt/archives/libjpeg-dev_8c-2ubuntu7_all.deb': No space left on device
cp: failed to extend '/var/cache/pbuilder/build//31985/var/cache/apt/archives/libjpeg-dev_8c-2ubuntu7_all.deb': No space left on device
cp: error writing '/var/cache/pbuilder/build//31985/var/cache/apt/archives/liburdfdom-sensor0.2_0.2.10+dfsg-1_amd64.deb': No space left on device
cp: failed to extend '/var/cache/pbuilder/build//31985/var/cache/apt/archives/liburdfdom-sensor0.2_0.2.10+dfsg-1_amd64.deb': No space left on device
cp: error writing '/var/cache/pbuilder/build//31985/var/cache/apt/archives/ros-indigo-pcl-conversions_0.2.0-0trusty-20150429-0753-+0000_amd64.deb': No space left on device
cp: failed to extend '/var/cache/pbuilder/build//31985/var/cache/apt/archives/ros-indigo-pcl-conversions_0.2.0-0trusty-20150429-0753-+0000_amd64.deb': No space left on device
cp: error writing '/var/cache/pbuilder/build//31985/var/cache/apt/archives/ros-indigo-rocon-ebnf_0.1.23-0trusty-20151110-2226-+0000_amd64.deb': No space left on device
cp: failed to extend '/var/cache/pbuilder/build//31985/var/cache/apt/archives/ros-indigo-rocon-ebnf_0.1.23-0trusty-20151110-2226-+0000_amd64.deb': No space left on device
cp: error writing '/var/cache/pbuilder/build//31985/var/cache/apt/archives/ros-indigo-rocon-interaction-msgs_0.7.9-0trusty-20150327-0426-+0000_amd64.deb': No space left on device
```

**Comment by marc-hanheide** [comment]
I think the problem is that https://lcas.lincoln.ac.uk/jenkins/job/pr-indigo-strands_navigation/142/ got aborted and that abortion of the process left the files stale, so still blocking the resources. That's a bug... I have cleared the stale processes now by rebooting the specific build machine. Let's try again.

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
so, now it works!

**Comment by hawesie** [comment]
I'm merging because test pass and it's not in the main stream of navigation, but is needed for testing the mdp executor which will need to be released soon.

**Pull request merged**
