### PR TITLE
Localise by topic 

### PR DESCRIPTION
**Pull request by Jailander**
Including persistency check on localise by topic, and localise_anywhere is now configurable on the localise by topic string

There is a short README on: https://github.com/Jailander/strands_navigation/tree/localise-by-topic-r2/topological_navigation#using-localise-by-topic

### CODE REVIEW

**Comment by Jailander** [comment]
Tested on simulation and Linda, @bfalacerda would you mind giving it a try? just for making sure it works as usual everywhere

**Comment by bfalacerda** [comment]
Both our charging stations are in G4S, so the best I can do is plug and unplug betty a couple of times. Not very useful...

**Comment by Jailander** [comment]
Ok not a problem I'll do more intensive tests in Linda then, but I think is good to go

**Comment by marc-hanheide** [comment]
Is this what is being used on Werner?

**Comment by Jailander** [comment]
yes, this was to fix the problem we had when the robot thought it was at the charging station because the charging topic changed once at the middle of the corridor and navigation failed

**Pull request merged**
