### PR TITLE
Implementing service lock for topological prediction

### PR DESCRIPTION
**Pull request by Jailander**
Printing messages for debugging, Implementing service lock for topological prediction to avoid collisions when calling the service more than once, making navigation nodes respawnable

### CODE REVIEW

**Comment by marc-hanheide** [comment]
quite an extensive changeset, the lock is one line and the additional logging statements are fine to, but what is the rest big set of changes implementing (Of course, I don't mena the "respawn" that's fine as well.)?

**Comment by Jailander** [comment]
yes they are but we have tested them os to make sure that if the fremenserver is respawned the models are rebuilt I tested it seems to work fine

**Comment by Jailander** [comment]
@marc-hanheide can we merge this its been in werner for a few days without incidents (however the robot hasn't moved much) and I need to change a few things in topological prediction for tsc (don't want to create unnecessary conflicts

**Comment by Jailander** [comment]
thank you :)

**Pull request merged**
