### PR TITLE
Bug Fix with inc variable not being set on special cases

### PR DESCRIPTION
**Pull request by Jailander**

### CODE REVIEW

**Comment by hawesie** [comment]
Have you tested it?

**Comment by Jailander** [comment]
no, I can't however this is how I should have done it

**Comment by Jailander** [comment]
@lucasb-eyer fix suggested in #159 would mean that the robot retries a lot less

**Comment by lucasb-eyer** [comment]
I don't believe this works: The indentation is off.

**Comment by hawesie** [comment]
@lucasb-eyer yeah, that's what made me nervous

**Comment by Jailander** [comment]
:( sorry as I said couldn't test not on my pc and vim on this PC doesn't have add-ons now it should be fixed

**Comment by lucasb-eyer** [comment]
`:set list`, thank me later ;-)

**Comment by Jailander** [comment]
this also includes fix for #160

**Comment by bfalacerda** [comment]
is this tested? isnt it tackling a killer bug? we need to get it  in the system
ill test a bit once bob has a  bit of battery

**Comment by lucasb-eyer** [comment]
Just fyi, I didn't test it.

**Comment by Jailander** [comment]
No is not tested and wasn't going to work, I just added a fix will test at 12.30 and then will report please don't merge until tested

**Comment by Jailander** [comment]
Ok @BFALacerda if you have a suitable sim can you test too, please?

**Comment by bfalacerda** [comment]
bob is out of commission so i can test there before starting the run

**Comment by Jailander** [comment]
Ok we are still waiting for access to the charging station

**Comment by bfalacerda** [comment]
i can make him publih ChargingPont in /current_node without having him docked

**Comment by Jailander** [comment]
@BFALacerda we tested it here (not intensively as we had to leave again) seemed to work fine and solve the problem after 2.30 we will have more trials

**Comment by bfalacerda** [comment]
bob is using this code and it doesnt crash, but i thought it was suppose to never say his current_node is ChargingPoint when he's not docked and it does. If he fails to dock and thinks he's at ChargingPoint he probably won't try again

**Comment by hawesie** [comment]
@Jailander @lucasb-eyer @BFALacerda do we want to merge and release this? It doesn't fix the problem but does it stop the inc-related crash?

**Comment by bfalacerda** [comment]
Bob's been using this and he never had the inc issue

**Comment by Jailander** [comment]
yes the inc Issue was fixed on the first commit, the other problem is more conceptual, to completely solve it we would need to have access to the charging information somehow, however as I said with last changes and a reasonable station to ChargingPoint distance and a very small influence zone for ChargingPoint that problem should not happen again

**Comment by hawesie** [comment]
@Jailander please could you post on gitter an acceptably small influence zone so everyone can copy it?

**Comment by Jailander** [comment]
yes will do

**Pull request merged**
