### PR TITLE
 Topological navigation doesn't use nasty old Classes anymore

### PR DESCRIPTION
**Pull request by Jailander**
Also:
- Fixes bug in Topological Localisation
- Does reconfigure move_base depending on edge configuration
- Unifies some utilities in one file
- Cleans code

### CODE REVIEW

**Comment by hawesie** [comment]
@bfalacerda can you restart Bob with this in the 1f workspace?

**Comment by Jailander** [comment]
I found a bug in the migrate script that causes edges not to have ids this PR would cause faulty behaviour on this case, I will fix migrate script and reopen but running migrate script again may be required

**Comment by Jailander** [comment]
Now if you have problems with topological navigation, just do:
`rosrun topological_utils migrate.py`
that should fix faulty maps

**Comment by bfalacerda** [comment]
Tomorrow I'll test this (I dont think I merged the last commit to Bob, what does it do btw?), and then we should merge it

**Comment by Jailander** [comment]
Now it doesn't count failures for time estimation

**Comment by cdondrup** [comment]
I am having this issue:

```
Traceback (most recent call last):                                                                                                               │··································································
  File "/localhome/strands/cdondrup/src/strands_navigation/topological_navigation/scripts/topological_prediction.py", line 248, in <module>      │··································································
    server = TopologicalNavPred(rospy.get_name())                                                                                                │··································································
  File "/localhome/strands/cdondrup/src/strands_navigation/topological_navigation/scripts/topological_prediction.py", line 83, in __init__       │··································································
    self.get_list_of_edges()                                                                                                                     │··································································
  File "/localhome/strands/cdondrup/src/strands_navigation/topological_navigation/scripts/topological_prediction.py", line 153, in get_list_of_e$│··································································
ges                                                                                                                                              │··································································
    val["dist"]= node_dist(i,ddn)/j.top_vel                                                                                                      │··································································
ZeroDivisionError: float division by zero
```

and @Jailander said it would be solved by this PR. Has this been tested yet?

**Comment by cdondrup** [comment]
Checked out @Jailander's fork, ran the migrate script and it seems to work. Just ran a simple test of letting the robot dock and undock and sending it around with rviz markers. Doesn't compensate for a proper test by @bfalacerda I guess, but at least it works in it's most basic form ;)

**Comment by bfalacerda** [comment]
we'll have bob running this for a while in the afternoon (last commit wasnt tested I think). I'll merge once bob runs around with it for a while

**Comment by Jailander** [comment]
needs https://github.com/strands-project/fremen/pull/16 to be merged

**Comment by Jailander** [comment]
REMEMBER if you experience any problems with topological navigation after merging do: `rosrun topological_utils migrate`

**Comment by bfalacerda** [comment]
execution is working fine, and the new prediction service is much faster. merging this

**Comment by Jailander** [comment]
yay!!!!

**Comment by Jailander** [comment]
wait for new PRs coming soon

**Pull request merged**
