### PR TITLE
merge topological-testing into indigo-devel

### PR DESCRIPTION
**Pull request by bfalacerda**
I think we're at a point where this has been tested enough to get into indigo-devel, and we can go back to forking and PRing into indigo-devel instead of having the extra branch.  Things are getting out of sync, e.g., https://github.com/strands-project/strands_executive/pull/135 just works with topological-testing.

@Jailander ?

### CODE REVIEW

**Comment by marc-hanheide** [comment]
woohoo... @bfalacerda @Jailander I presume you better approve this yourself.

**Comment by Jailander** [comment]
Yes I agree, can you check the changes I made last night too, the nodes you add form Rviz should be ok now too, I'll have a Readme by 5 p.m.

**Comment by Jailander** [comment]
I meant @bfalacerda ;-)

**Comment by bfalacerda** [comment]
will test soon the new things soon. In terms of readme, what is really important now is making sure everyone is aware of the migrate.py script, as they'll have to run it when this is merged otherwise they cant use the topological maps already in mongo

**Comment by marc-hanheide** [comment]
It might be worth sending an email on strands mailing list out once this has happended. As this will effect many people.

**Comment by bfalacerda** [comment]
true. even better would be running migrate.py as the final step of the install process of the debian package. is that possible?

**Comment by bfalacerda** [comment]
nevermind, it only works if mongo is running, so we can't really make it fully automatic i guess. Mail is less of an hassle

**Comment by marc-hanheide** [comment]
Yeah, that would be quite some effort... so better do it manully.

**Comment by marc-hanheide** [comment]
this is merging into indigo-devel, while jenkins is still configured to test hydro-devel. I suppose that is not intended?

**Comment by marc-hanheide** [comment]
Once https://github.com/strands-project/rosdistro/pull/400 is accepted, we can enable jenkins tests for this PR.

**Comment by bfalacerda** [comment]
:+1:

**Comment by bfalacerda** [comment]
there's stuff in hydro-devel that not merged into indigo-devel either, e.g., https://github.com/strands-project/strands_navigation/commit/c35e5f9bd674586b8d6ca9b4381ed997b12552b3

**Comment by marc-hanheide** [comment]
Oh dear... ok, tidy this up, and I'll move jenkins to use indigo-devel from now on so we get it checked.

**Comment by hawesie** [comment]
Sorry, I didn’t know about indigo-devel.

**Comment by marc-hanheide** [comment]
neither did I until now...

**Comment by bfalacerda** [comment]
Can I just make a PR from hydro-devel into indigo-devel? Or merge everything into my fork indigo-devel branch and then make a PR from there? I'm always unsure of how that affects the version numbering.

**Comment by marc-hanheide** [comment]
looking at https://github.com/strands-project/strands_navigation/compare/hydro-devel it seems we can merge it. But it also makes clear that people have been committing a lot to hydro-devel, because nobody knew indigo-devel existed. So, I suggest to open the hydro-devel->indigo-devel PR as well. Have them all checked... And you might end up with some of them not being mergeable automatically anymore... And then let's make sure people only submit PRs against indigo from now on!

**Comment by marc-hanheide** [comment]
see https://github.com/strands-project/strands_navigation/pull/194

**Comment by marc-hanheide** [comment]
retest this please

**Comment by bfalacerda** [comment]
closing, #195 subsumes this

**Pull request closed without merging**
